<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('countries')->delete();

        DB::table('countries')->insert([[
            'name' => 'Empty',
            'code' => 'EM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Afghanistan',
            'code' => 'AF',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Albania',
            'code' => 'AL',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Algeria',
            'code' => 'DZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'American Samoa',
            'code' => 'AS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:09:12',
        ], [
            'name' => 'Andorra',
            'code' => 'AD',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:09:21',
        ], [
            'name' => 'Angola',
            'code' => 'AO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Anguilla',
            'code' => 'AI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:09:33',
        ], [
            'name' => 'Antarctica',
            'code' => 'AQ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:02:37',
        ], [
            'name' => 'Antigua And Barbuda',
            'code' => 'AG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:09:39',
        ], [
            'name' => 'Argentina',
            'code' => 'AR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Armenia',
            'code' => 'AM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Aruba',
            'code' => 'AW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:09:50',
        ], [
            'name' => 'Australia',
            'code' => 'AU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Austria',
            'code' => 'AT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Azerbaijan',
            'code' => 'AZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Bahamas The',
            'code' => 'BS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:09:59',
        ], [
            'name' => 'Bahrain',
            'code' => 'BH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Bangladesh',
            'code' => 'BD',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Barbados',
            'code' => 'BB',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Belarus',
            'code' => 'BY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Belgium',
            'code' => 'BE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Belize',
            'code' => 'BZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:10:08',
        ], [
            'name' => 'Benin',
            'code' => 'BJ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:10:15',
        ], [
            'name' => 'Bermuda',
            'code' => 'BM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Bhutan',
            'code' => 'BT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Bolivia',
            'code' => 'BO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Bosnia and Herzegovina',
            'code' => 'BA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:10:34',
        ], [
            'name' => 'Botswana',
            'code' => 'BW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Bouvet Island',
            'code' => 'BV',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:10:39',
        ], [
            'name' => 'Brazil',
            'code' => 'BR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'British Indian Ocean Territory',
            'code' => 'IO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:10:53',
        ], [
            'name' => 'Brunei',
            'code' => 'BN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Bulgaria',
            'code' => 'BG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Burkina Faso',
            'code' => 'BF',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Burundi',
            'code' => 'BI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Cambodia',
            'code' => 'KH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Cameroon',
            'code' => 'CM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Canada',
            'code' => 'CA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Cape Verde',
            'code' => 'CV',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:11:06',
        ], [
            'name' => 'Cayman Islands',
            'code' => 'KY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:11:13',
        ], [
            'name' => 'Central African Republic',
            'code' => 'CF',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:11:21',
        ], [
            'name' => 'Chad',
            'code' => 'TD',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:11:26',
        ], [
            'name' => 'Chile',
            'code' => 'CL',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'China',
            'code' => 'CN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Christmas Island',
            'code' => 'CX',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:11:31',
        ], [
            'name' => 'Cocos (Keeling) Islands',
            'code' => 'CC',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:11:38',
        ], [
            'name' => 'Colombia',
            'code' => 'CO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Comoros',
            'code' => 'KM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Cook Islands',
            'code' => 'CK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:11:48',
        ], [
            'name' => 'Costa Rica',
            'code' => 'CR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Cote D\'Ivoire (Ivory Coast)',
            'code' => 'CI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:12:06',
        ], [
            'name' => 'Croatia (Hrvatska)',
            'code' => 'HR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Cuba',
            'code' => 'CU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Cyprus',
            'code' => 'CY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Czech Republic',
            'code' => 'CZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Democratic Republic Of The Congo',
            'code' => 'CD',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Denmark',
            'code' => 'DK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Djibouti',
            'code' => 'DJ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Dominica',
            'code' => 'DM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:12:34',
        ], [
            'name' => 'Dominican Republic',
            'code' => 'DO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'East Timor',
            'code' => 'TP',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:12:40',
        ], [
            'name' => 'Ecuador',
            'code' => 'EC',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Egypt',
            'code' => 'EG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'El Salvador',
            'code' => 'SV',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:12:47',
        ], [
            'name' => 'Equatorial Guinea',
            'code' => 'GQ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:12:51',
        ], [
            'name' => 'Eritrea',
            'code' => 'ER',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:13:21',
        ], [
            'name' => 'Estonia',
            'code' => 'EE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Ethiopia',
            'code' => 'ET',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Falkland Islands',
            'code' => 'FK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:13:26',
        ], [
            'name' => 'Faroe Islands',
            'code' => 'FO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:13:31',
        ], [
            'name' => 'Fiji Islands',
            'code' => 'FJ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:13:36',
        ], [
            'name' => 'Finland',
            'code' => 'FI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'France',
            'code' => 'FR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'French Guiana',
            'code' => 'GF',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:13:42',
        ], [
            'name' => 'French Polynesia',
            'code' => 'PF',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:13:45',
        ], [
            'name' => 'French Southern Territories',
            'code' => 'TF',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:13:55',
        ], [
            'name' => 'Gabon',
            'code' => 'GA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:01',
        ], [
            'name' => 'Gambia The',
            'code' => 'GM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:05',
        ], [
            'name' => 'Georgia',
            'code' => 'GE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Germany',
            'code' => 'DE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Ghana',
            'code' => 'GH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Gibraltar',
            'code' => 'GI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:14',
        ], [
            'name' => 'Greece',
            'code' => 'GR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Greenland',
            'code' => 'GL',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Grenada',
            'code' => 'GD',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:23',
        ], [
            'name' => 'Guadeloupe',
            'code' => 'GP',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:27',
        ], [
            'name' => 'Guam',
            'code' => 'GU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:32',
        ], [
            'name' => 'Guatemala',
            'code' => 'GT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:38',
        ], [
            'name' => 'Guernsey and Alderney',
            'code' => 'XU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:41',
        ], [
            'name' => 'Guinea',
            'code' => 'GN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Guinea-Bissau',
            'code' => 'GW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Guyana',
            'code' => 'GY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Haiti',
            'code' => 'HT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:55',
        ], [
            'name' => 'Heard and McDonald Islands',
            'code' => 'HM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:52',
        ], [
            'name' => 'Honduras',
            'code' => 'HN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:14:59',
        ], [
            'name' => 'Hong Kong S.A.R.',
            'code' => 'HK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:15:06',
        ], [
            'name' => 'Hungary',
            'code' => 'HU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Iceland',
            'code' => 'IS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'India',
            'code' => 'IN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Indonesia',
            'code' => 'ID',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Iran',
            'code' => 'IR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Iraq',
            'code' => 'IQ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Ireland',
            'code' => 'IE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Israel',
            'code' => 'IL',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Italy',
            'code' => 'IT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Jamaica',
            'code' => 'JM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Japan',
            'code' => 'JP',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Jersey',
            'code' => 'XJ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Jordan',
            'code' => 'JO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Kazakhstan',
            'code' => 'KZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Kenya',
            'code' => 'KE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Kiribati',
            'code' => 'KI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Korea North',
            'code' => 'KP',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Korea South',
            'code' => 'KR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Kuwait',
            'code' => 'KW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Kyrgyzstan',
            'code' => 'KG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Laos',
            'code' => 'LA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Latvia',
            'code' => 'LV',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Lebanon',
            'code' => 'LB',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Lesotho',
            'code' => 'LS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Liberia',
            'code' => 'LR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Libya',
            'code' => 'LY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Liechtenstein',
            'code' => 'LI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:15:51',
        ], [
            'name' => 'Lithuania',
            'code' => 'LT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:15:57',
        ], [
            'name' => 'Luxembourg',
            'code' => 'LU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Macau S.A.R.',
            'code' => 'MO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Macedonia',
            'code' => 'MK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Madagascar',
            'code' => 'MG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:16:27',
        ], [
            'name' => 'Malawi',
            'code' => 'MW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Malaysia',
            'code' => 'MY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Maldives',
            'code' => 'MV',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Mali',
            'code' => 'ML',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Malta',
            'code' => 'MT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Man (Isle of)',
            'code' => 'XM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:16:38',
        ], [
            'name' => 'Marshall Islands',
            'code' => 'MH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:16:54',
        ], [
            'name' => 'Martinique',
            'code' => 'MQ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:16:57',
        ], [
            'name' => 'Mauritania',
            'code' => 'MR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:17:05',
        ], [
            'name' => 'Mauritius',
            'code' => 'MU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Mayotte',
            'code' => 'YT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:17:11',
        ], [
            'name' => 'Mexico',
            'code' => 'MX',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Micronesia',
            'code' => 'FM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:17:19',
        ], [
            'name' => 'Moldova',
            'code' => 'MD',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:17:25',
        ], [
            'name' => 'Monaco',
            'code' => 'MC',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:17:29',
        ], [
            'name' => 'Mongolia',
            'code' => 'MN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Montserrat',
            'code' => 'MS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:17:40',
        ], [
            'name' => 'Morocco',
            'code' => 'MA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Mozambique',
            'code' => 'MZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Myanmar',
            'code' => 'MM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Namibia',
            'code' => 'NA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Nauru',
            'code' => 'NR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:17:49',
        ], [
            'name' => 'Nepal',
            'code' => 'NP',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Netherlands Antilles',
            'code' => 'AN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:18:11',
        ], [
            'name' => 'Netherlands The',
            'code' => 'NL',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'New Caledonia',
            'code' => 'NC',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:18:20',
        ], [
            'name' => 'New Zealand',
            'code' => 'NZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Nicaragua',
            'code' => 'NI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:18:25',
        ], [
            'name' => 'Niger',
            'code' => 'NE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:18:32',
        ], [
            'name' => 'Nigeria',
            'code' => 'NG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Niue',
            'code' => 'NU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:18:36',
        ], [
            'name' => 'Norfolk Island',
            'code' => 'NF',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:18:42',
        ], [
            'name' => 'Northern Mariana Islands',
            'code' => 'MP',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:18:50',
        ], [
            'name' => 'Norway',
            'code' => 'NO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Oman',
            'code' => 'OM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Pakistan',
            'code' => 'PK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Palau',
            'code' => 'PW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:18:57',
        ], [
            'name' => 'Palestinian Territory Occupied',
            'code' => 'PS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:19:02',
        ], [
            'name' => 'Panama',
            'code' => 'PA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Papua new Guinea',
            'code' => 'PG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Paraguay',
            'code' => 'PY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Peru',
            'code' => 'PE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Philippines',
            'code' => 'PH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Pitcairn Island',
            'code' => 'PN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:19:11',
        ], [
            'name' => 'Poland',
            'code' => 'PL',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Portugal',
            'code' => 'PT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Puerto Rico',
            'code' => 'PR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Qatar',
            'code' => 'QA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Republic Of The Congo',
            'code' => 'CG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Reunion',
            'code' => 'RE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:19:26',
        ], [
            'name' => 'Romania',
            'code' => 'RO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Russia',
            'code' => 'RU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Rwanda',
            'code' => 'RW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Saint Helena',
            'code' => 'SH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:19:40',
        ], [
            'name' => 'Saint Kitts And Nevis',
            'code' => 'KN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:19:44',
        ], [
            'name' => 'Saint Lucia',
            'code' => 'LC',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Saint Pierre and Miquelon',
            'code' => 'PM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Saint Vincent And The Grenadines',
            'code' => 'VC',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Samoa',
            'code' => 'WS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'San Marino',
            'code' => 'SM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Sao Tome and Principe',
            'code' => 'ST',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Saudi Arabia',
            'code' => 'SA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Senegal',
            'code' => 'SN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Serbia',
            'code' => 'RS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Seychelles',
            'code' => 'SC',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Sierra Leone',
            'code' => 'SL',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Singapore',
            'code' => 'SG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Slovakia',
            'code' => 'SK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Slovenia',
            'code' => 'SI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Smaller Territories of the UK',
            'code' => 'XG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:20:18',
        ], [
            'name' => 'Solomon Islands',
            'code' => 'SB',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:20:23',
        ], [
            'name' => 'Somalia',
            'code' => 'SO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'South Africa',
            'code' => 'ZA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'South Georgia',
            'code' => 'GS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'South Sudan',
            'code' => 'SS',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:20:41',
        ], [
            'name' => 'Spain',
            'code' => 'ES',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Sri Lanka',
            'code' => 'LK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Sudan',
            'code' => 'SD',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Suriname',
            'code' => 'SR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:21:06',
        ], [
            'name' => 'Svalbard And Jan Mayen Islands',
            'code' => 'SJ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:21:00',
        ], [
            'name' => 'Swaziland',
            'code' => 'SZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:21:12',
        ], [
            'name' => 'Sweden',
            'code' => 'SE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Switzerland',
            'code' => 'CH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Syria',
            'code' => 'SY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Taiwan',
            'code' => 'TW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Tajikistan',
            'code' => 'TJ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Tanzania',
            'code' => 'TZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Thailand',
            'code' => 'TH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Togo',
            'code' => 'TG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Tokelau',
            'code' => 'TK',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Tonga',
            'code' => 'TO',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Trinidad And Tobago',
            'code' => 'TT',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Tunisia',
            'code' => 'TN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Turkey',
            'code' => 'TR',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Turkmenistan',
            'code' => 'TM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Turks And Caicos Islands',
            'code' => 'TC',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:21:31',
        ], [
            'name' => 'Tuvalu',
            'code' => 'TV',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:21:37',
        ], [
            'name' => 'Uganda',
            'code' => 'UG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Ukraine',
            'code' => 'UA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'United Arab Emirates',
            'code' => 'AE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'United Kingdom',
            'code' => 'GB',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'United States',
            'code' => 'US',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'United States Minor Outlying Islands',
            'code' => 'UM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:21:52',
        ], [
            'name' => 'Uruguay',
            'code' => 'UY',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Uzbekistan',
            'code' => 'UZ',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Vanuatu',
            'code' => 'VU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:21:58',
        ], [
            'name' => 'Vatican City State (Holy See)',
            'code' => 'VA',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:22:08',
        ], [
            'name' => 'Venezuela',
            'code' => 'VE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Vietnam',
            'code' => 'VN',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Virgin Islands (British)',
            'code' => 'VG',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:22:15',
        ], [
            'name' => 'Virgin Islands (US)',
            'code' => 'VI',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:22:20',
        ], [
            'name' => 'Wallis And Futuna Islands',
            'code' => 'WF',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:22:28',
        ], [
            'name' => 'Western Sahara',
            'code' => 'EH',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => '2024-03-07 23:22:33',
        ], [
            'name' => 'Yemen',
            'code' => 'YE',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Yugoslavia',
            'code' => 'YU',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Zambia',
            'code' => 'ZM',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ], [
            'name' => 'Zimbabwe',
            'code' => 'ZW',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
            'created_by' => 1,
            'updated_by' => 1,
            'deleted_at' => NULL,
        ]]);
    }
}
